# TSA Prediction Project Configuration

data:
  # API Keys (load from environment variables)
  weather_api_key: ${WEATHER_API_KEY}
  airline_api_key: ${AIRLINE_API_KEY}
  
  # Data Sources
  tsa_data_url: "https://www.tsa.gov/coronavirus/passenger-throughput"
  
  # Directory paths (relative to project root)
  data_directory: "data/raw"
  snapshot_directory: "data/processed/snapshots"
  
  # Data collection settings
  major_airports:
    - "ATL"  # Atlanta
    - "LAX"  # Los Angeles
    - "ORD"  # Chicago O'Hare
    - "DFW"  # Dallas/Fort Worth
    - "DEN"  # Denver
    - "JFK"  # New York JFK
    - "SFO"  # San Francisco
    - "SEA"  # Seattle
    - "LAS"  # Las Vegas
    - "MCO"  # Orlando

  update_frequency:
    tsa: 24        # hours
    weather: 1     # hours
    airlines: 48   # hours
    hotels: 72     # hours
    economic: 168  # hours

model:
  prediction_horizon: 7  # days (for weekly prediction)
  feature_lookback: 90  # days of historical data to use
  train_start_date: "2020-01-01"
  test_start_date: "2023-01-01"
  random_seed: 42
  
  feature_groups:
    - "calendar"      # holidays, day of week, etc.
    - "weather"       # weather patterns at major airports
    - "airline"       # pricing and capacity
    - "economic"      # economic indicators
    - "seasonality"   # seasonal patterns

trading:
  # Kalshi credentials (load from environment variables)
  kalshi_api_key_id: ${KALSHI_API_KEY_ID}  # Your API key ID
  kalshi_private_key_path: "secrets/kalshi_private_key.pem"  # Path to private key file
  
  kalshi_env: "production"  # or "demo"
  market_id: "kxtsaw"      # TSA checkins market ID
  
  # Position sizing
  max_position_size: 1000.0  # max dollar amount per trade
  risk_limit: 5000.0        # max total risk exposure
  min_edge: 0.05           # minimum edge required to trade
  
  # Risk management
  stop_loss: 0.15          # 15% maximum loss per position
  position_limits:
    daily: 3               # max number of new positions per day
    total: 10              # max total open positions

backtesting:
  initial_capital: 10000.0
  transaction_cost: 0.001   # 10 basis points
  slippage: 0.001          # 10 basis points
  
  benchmark: "SP500"
  risk_free_rate: 0.02     # 2% annual risk-free rate
  
  monte_carlo_sims: 1000
  confidence_level: 0.95

logging:
  level: "INFO"
  log_file: "logs/tsa_prediction.log"
  console_output: true
  
  monitor_metrics:
    - "prediction_accuracy"
    - "sharpe_ratio"
    - "max_drawdown"
    - "win_rate"
  
  alert_thresholds:
    max_drawdown: 0.2      # alert if drawdown exceeds 20%
    prediction_error: 0.15  # alert if prediction error exceeds 15%